universe   = vanilla
initialdir = /home/gtirpitz/plainCV

executable = cluster/preprocess/condor.sh
arguments  =

output = job_outputs/prep_fwedu.$(Cluster).$(Process).out
error  = job_outputs/prep_fwedu.$(Cluster).$(Process).err
log    = job_outputs/prep_fwedu.$(Cluster).log

request_cpus   = 4
request_memory = 65536
request_gpus   = 0

getenv = True

+JobBatchName = "plaincv-fwedu-prep"
+MaxTime = 7200

queue 1
