"""Shared loading + allocation-gain math for the Section-C analyses (C1-C5).

The object of study is how an optimizer *places* its update energy across the
87 contiguous parameter blocks, scored against the placement that would maximise
the first-order gain at the same checkpoint.

For an allocation ``w`` over blocks (``w_b >= 0``, ``sum_b w_b = 1``), with
per-block first-order gain coefficient ``beta_b`` and per-block curvature
exposure ``A_b``:

    G(w)  = (sum_b sqrt(w_b) beta_b)^2 / sum_b w_b (A_b + delta)     gain
    G*    = sum_b beta_b^2 / (A_b + delta)                           optimal gain
    R     = G(w) / G*                                                in [0, 1]
    w*_b  proportional to (beta_b / (A_b + delta))^2                 optimum
    cert(w) = sum_b w_b AM_b / AM                                    block certificate

``delta`` is a damping set as a fraction of the block-diagonal exposure
``sum_b w_b A_b``; it keeps ``G*`` finite when some block has ``A_b -> 0``.

Two ``beta`` channels are supported:
  * ``proxy``    -- ``beta_b^2 = size_b * AM_b`` (no gradient logging needed)
  * ``measured`` -- ``beta_b^2 = block_gnorm2_b * block_cos_b^2`` (needs the A1/A2
    columns from ``section1_measures``)
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from typing import Optional

import numpy as np
import pandas as pd

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LM_RUNS = os.path.join(REPO, "exp", "paper_runs", "llm")
VIT_RUNS = os.path.join(REPO, "exp", "paper_runs", "vit")

# job_idx -> seed, as generated by run_all_seeds.sh (SEED_LIST order).
JOB_IDX_TO_SEED = {0: 0, 1: 42, 2: 137}

W_FLOOR = 1e-12
DELTA_FRAC_DEFAULT = 1e-3

# Arms are not measured on the same step grid. SOAP runs with
# eigen_tracking_post_soap_refresh, so its first probe lands at
# precondition_frequency + 2 = 34 and every later checkpoint is offset by the
# same +34: 610, 1186, ..., 9250, ..., 12130 against the other arms' 576, 1152,
# ..., 9216, ..., 12672. Matching arms on exact global_step therefore drops SOAP
# from every cross-arm view. Checkpoints within STEP_TOL of each other are the
# same measurement occasion and are clustered onto one label.
STEP_TOL_DEFAULT = 64


@dataclass
class Run:
    """One training run's Section-1 measures plus its static block tags."""

    family: str          # "lm" | "vit"
    optimizer: str
    seed: int
    job_idx: int
    path: str
    measures: pd.DataFrame
    tags: pd.DataFrame

    @property
    def n_blocks(self) -> int:
        return len(self.tags)

    @property
    def namesake(self) -> np.ndarray:
        return self.tags["namesake"].to_numpy().astype(bool)

    @property
    def sizes(self) -> np.ndarray:
        return self.tags["size"].to_numpy().astype(np.float64)

    @property
    def label(self) -> str:
        return f"{self.family}/{self.optimizer}/s{self.seed}"


def _block_array(df_row: pd.Series, prefix: str, n_blocks: int) -> np.ndarray:
    """Pull ``prefix_0 .. prefix_{n-1}`` out of one CSV row as a float array."""
    cols = [f"{prefix}_{b}" for b in range(n_blocks)]
    missing = [c for c in cols if c not in df_row.index]
    if missing:
        return np.full(n_blocks, np.nan)
    return df_row[cols].to_numpy(dtype=np.float64)


def has_columns(run: Run, prefix: str) -> bool:
    return f"{prefix}_0" in run.measures.columns


def discover_runs(family: str = "lm", root: Optional[str] = None) -> list:
    """Find every run under the paper-runs tree that has Section-1 measures."""
    root = root or (LM_RUNS if family == "lm" else VIT_RUNS)
    runs: list = []
    if not os.path.isdir(root):
        return runs
    for arm in sorted(os.listdir(root)):
        arm_dir = os.path.join(root, arm)
        if not os.path.isdir(arm_dir):
            continue
        m = re.match(r"GGN_(?:vit_tinyimagenet_)?(.+?)_seeds$", arm)
        optimizer = m.group(1) if m else arm
        for job in sorted(os.listdir(arm_dir)):
            job_dir = os.path.join(arm_dir, job)
            meas = os.path.join(job_dir, "section1_measures.csv")
            tags = os.path.join(job_dir, "section1_block_tags.csv")
            if not (os.path.isfile(meas) and os.path.isfile(tags)):
                continue
            jm = re.match(r"job_idx_(\d+)$", job)
            job_idx = int(jm.group(1)) if jm else -1
            runs.append(
                Run(
                    family=family,
                    optimizer=optimizer,
                    seed=JOB_IDX_TO_SEED.get(job_idx, job_idx),
                    job_idx=job_idx,
                    path=job_dir,
                    measures=pd.read_csv(meas),
                    tags=pd.read_csv(tags),
                )
            )
    return runs


@dataclass
class Checkpoint:
    """One measurement row reduced to the blocks that carry a defined gain."""

    run: Run
    global_step: int
    valid: np.ndarray     # bool mask over all blocks
    w: np.ndarray         # allocation over valid blocks, renormalized to sum 1
    A: np.ndarray         # block Rayleigh exposure A_b
    AM: np.ndarray        # block arithmetic-mean curvature AM_b
    beta2: np.ndarray     # squared first-order gain coefficient
    size: np.ndarray
    namesake: np.ndarray
    AM_full: float        # full-space AM reference for the certificate
    channel: str

    @property
    def n(self) -> int:
        return int(self.w.size)


def build_checkpoint(
    run: Run,
    row: pd.Series,
    channel: str = "proxy",
) -> Optional[Checkpoint]:
    """Reduce one measurement row to a Checkpoint, or None if unusable.

    Blocks are kept when ``w_b > 1e-12``, ``A_b > 0`` and ``AM_b > 0``; the
    surviving ``w`` is renormalized so it remains a probability vector.
    """
    n = run.n_blocks
    w_raw = _block_array(row, "block_w", n)
    A = _block_array(row, "block_A", n)
    AM = _block_array(row, "block_AM", n)

    if channel == "proxy":
        beta2 = run.sizes * AM
    elif channel == "measured":
        gn2 = _block_array(row, "block_gnorm2", n)
        cos = _block_array(row, "block_cos", n)
        beta2 = gn2 * np.square(cos)
    else:
        raise ValueError(f"unknown beta channel {channel!r}")

    valid = (
        np.isfinite(w_raw) & (w_raw > W_FLOOR)
        & np.isfinite(A) & (A > 0)
        & np.isfinite(AM) & (AM > 0)
        & np.isfinite(beta2) & (beta2 >= 0)
    )
    if valid.sum() < 2:
        return None

    w = w_raw[valid]
    w = w / w.sum()
    return Checkpoint(
        run=run,
        global_step=int(row["global_step"]),
        valid=valid,
        w=w,
        A=A[valid],
        AM=AM[valid],
        beta2=beta2[valid],
        size=run.sizes[valid],
        namesake=run.namesake[valid],
        AM_full=float(row["AM"]),
        channel=channel,
    )


def damping(ck: Checkpoint, frac: float = DELTA_FRAC_DEFAULT) -> float:
    """delta = frac * (block-diagonal exposure sum_b w_b A_b) over valid blocks."""
    return float(frac) * float(np.sum(ck.w * ck.A))


def gain(w: np.ndarray, beta2: np.ndarray, A: np.ndarray, delta: float) -> float:
    """G(w) = (sum_b sqrt(w_b) beta_b)^2 / sum_b w_b (A_b + delta)."""
    num = np.square(np.sum(np.sqrt(np.maximum(w, 0.0) * beta2)))
    den = np.sum(w * (A + delta))
    return float(num / den) if den > 0 else float("nan")


def optimal_gain(beta2: np.ndarray, A: np.ndarray, delta: float) -> float:
    """G* = sum_b beta_b^2 / (A_b + delta)."""
    return float(np.sum(beta2 / (A + delta)))


def optimal_w(beta2: np.ndarray, A: np.ndarray, delta: float) -> np.ndarray:
    """w*_b proportional to (beta_b / (A_b + delta))^2, normalized to sum 1."""
    unnorm = beta2 / np.square(A + delta)
    total = unnorm.sum()
    if not np.isfinite(total) or total <= 0:
        return np.full_like(unnorm, np.nan)
    return unnorm / total


def certificate(w: np.ndarray, AM: np.ndarray, AM_full: float) -> float:
    """cert(w) = sum_b w_b AM_b / AM (block-level, GD-rung reference)."""
    if not np.isfinite(AM_full) or AM_full <= 0:
        return float("nan")
    return float(np.sum(w * AM) / AM_full)


def spearman(x: np.ndarray, y: np.ndarray) -> float:
    """Spearman rank correlation, NaN-safe, NaN when it is not defined."""
    ok = np.isfinite(x) & np.isfinite(y)
    if ok.sum() < 3:
        return float("nan")
    from scipy.stats import spearmanr

    rho = spearmanr(x[ok], y[ok]).statistic
    return float(rho) if np.isfinite(rho) else float("nan")


def score_allocation(
    ck: Checkpoint,
    w: Optional[np.ndarray] = None,
    delta_frac: float = DELTA_FRAC_DEFAULT,
) -> dict:
    """R, cert, namesake share and w-vs-w* Spearman for one allocation."""
    w = ck.w if w is None else w
    delta = damping(ck, delta_frac)
    G = gain(w, ck.beta2, ck.A, delta)
    Gstar = optimal_gain(ck.beta2, ck.A, delta)
    wstar = optimal_w(ck.beta2, ck.A, delta)
    return {
        "R": float(G / Gstar) if Gstar > 0 else float("nan"),
        "G": G,
        "G_star": Gstar,
        "cert": certificate(w, ck.AM, ck.AM_full),
        "namesake_share": float(np.sum(w[ck.namesake])),
        "spearman_w_wstar": spearman(w, wstar),
        "delta": delta,
        "n_blocks_valid": ck.n,
    }


def rescale_fallback(ck: Checkpoint, rho: float) -> np.ndarray:
    """Multiply fallback-block *energies* by rho^2 and renormalize (C2).

    Directions are held fixed: beta_b and A_b are the measured ones, only the
    energy split between namesake and fallback blocks moves. This is an
    instantaneous, same-checkpoint counterfactual -- it does not model how
    training would have evolved under a different fallback ratio.
    """
    w = ck.w.copy()
    w[~ck.namesake] *= float(rho) ** 2
    total = w.sum()
    return w / total if total > 0 else np.full_like(w, np.nan)


def rho_for_namesake_share(ck: Checkpoint, target: float = 0.5) -> float:
    """rho making the namesake energy share equal ``target`` after rescaling."""
    s_ns = float(np.sum(ck.w[ck.namesake]))
    s_fb = float(np.sum(ck.w[~ck.namesake]))
    if s_fb <= 0 or s_ns <= 0 or not (0.0 < target < 1.0):
        return float("nan")
    # s_ns / (s_ns + rho^2 s_fb) = target
    return float(np.sqrt((s_ns * (1.0 - target)) / (target * s_fb)))


def namesake_only(ck: Checkpoint) -> Optional[tuple]:
    """Restrict to namesake blocks, renormalizing w over them (C2)."""
    m = ck.namesake
    if m.sum() < 2 or ck.w[m].sum() <= 0:
        return None
    sub = Checkpoint(
        run=ck.run,
        global_step=ck.global_step,
        valid=ck.valid,
        w=ck.w[m] / ck.w[m].sum(),
        A=ck.A[m],
        AM=ck.AM[m],
        beta2=ck.beta2[m],
        size=ck.size[m],
        namesake=ck.namesake[m],
        AM_full=ck.AM_full,
        channel=ck.channel,
    )
    return (sub,)


def checkpoint_map(runs: list, tol: float = STEP_TOL_DEFAULT) -> dict:
    """Map each run's ``global_step`` onto a shared checkpoint label.

    Single-linkage clustering over the pooled steps: consecutive steps closer
    than ``tol`` belong to the same measurement occasion. Each cluster is
    labelled by its smallest member, so the majority arms keep their own grid
    (576, 1152, ...) and SOAP's +34 offset folds into it. A step with no
    neighbour within ``tol`` -- SOAP's transient first probe at 34 -- forms its
    own cluster and simply has no counterpart in the other arms.
    """
    steps = np.unique(
        np.concatenate(
            [r.measures["global_step"].to_numpy(dtype=np.int64) for r in runs]
        )
    )
    if steps.size == 0:
        return {}
    breaks = np.where(np.diff(steps) > tol)[0]
    mapping = {}
    for group in np.split(steps, breaks + 1):
        label = int(group.min())
        for s in group:
            mapping[int(s)] = label
    return mapping


def matched_step_of(mapping: dict, step: int) -> int:
    """Shared checkpoint label for ``step`` (identity when unmapped)."""
    return int(mapping.get(int(step), int(step)))


def iter_checkpoints(runs: list, channel: str = "proxy"):
    """Yield (run, Checkpoint) for every measurement row of every run."""
    for run in runs:
        for _, row in run.measures.iterrows():
            ck = build_checkpoint(run, row, channel=channel)
            if ck is not None:
                yield run, ck


def late_half(
    df: pd.DataFrame,
    step_col: str = "matched_step",
    group_cols: Optional[list] = None,
) -> pd.DataFrame:
    """Second half of the checkpoints of each trajectory.

    Matches compute_paper_quantities' late-training window, which is where the
    paper's headline numbers are read off; the early checkpoints sit in a
    different training phase and pull the run-averaged values down.

    ``group_cols`` defaults to (optimizer, seed); pass a longer list when the
    frame stacks several settings, so the halving happens within each one.
    """
    group_cols = group_cols or ["optimizer", "seed"]
    group_cols = [c for c in group_cols if c in df.columns]
    if not group_cols or df.empty:
        return df
    keep = []
    for _, sub in df.groupby(group_cols, sort=False):
        sub = sub.sort_values(step_col)
        keep.append(sub.iloc[len(sub) // 2:])
    return pd.concat(keep, ignore_index=True) if keep else df


def seed_summary(df: pd.DataFrame, group_cols: list, value_cols: list) -> pd.DataFrame:
    """Mean +/- sd across seeds, after averaging within each seed."""
    per_seed = df.groupby(group_cols + ["seed"], as_index=False)[value_cols].mean()
    agg = per_seed.groupby(group_cols, as_index=False).agg(
        {**{c: ["mean", "std", "count"] for c in value_cols}}
    )
    agg.columns = group_cols + [
        f"{c}_{stat}" for c in value_cols for stat in ("mean", "sd", "n")
    ]
    return agg


def out_dir(name: str) -> str:
    d = os.path.join(REPO, "analysis", name)
    os.makedirs(d, exist_ok=True)
    return d


# ---------------------------------------------------------------------------
# Section-3 (E/F/G): the eigen-tracking panel
#
# E, F and G read ``eigen_tracking.csv`` rather than ``section1_measures.csv``,
# so they run on ViT too (which has no Section-1 wiring). Everything below is
# shared by the three scripts so the guards, the checkpoint clustering and the
# arm taxonomy cannot drift apart between them.
# ---------------------------------------------------------------------------

MAIN_BODY_OPTIMIZERS = ("sgd", "signum", "adam", "muon", "soap")
CONTROL_OPTIMIZERS = ("hadamard-signum", "kaon")


def canonical_optimizer(name: str) -> str:
    """One spelling per optimizer across architectures.

    The LM arm directory is ``GGN_hadamard-signum_seeds`` while the ViT one is
    ``GGN_vit_tinyimagenet_hadamard_signum_seeds``; without normalizing, the two
    architectures would report two different optimizers.
    """
    return name.strip().lower().replace("_", "-")


def optimizer_family(name: str) -> str:
    """``main`` for the five main-body arms, ``control`` for the ablations."""
    return "main" if canonical_optimizer(name) in MAIN_BODY_OPTIMIZERS else "control"


def discover_eigen_runs(family: str = "lm", root: Optional[str] = None) -> list:
    """Every run under the paper-runs tree that has ``eigen_tracking.csv``.

    Mirrors :func:`discover_runs`, but the Section-1 CSVs are optional: ``tags``
    is left empty when they are absent, which is the normal state on ViT.
    """
    root = root or (LM_RUNS if family == "lm" else VIT_RUNS)
    runs: list = []
    if not os.path.isdir(root):
        return runs
    for arm in sorted(os.listdir(root)):
        arm_dir = os.path.join(root, arm)
        if not os.path.isdir(arm_dir):
            continue
        m = re.match(r"GGN_(?:vit_tinyimagenet_)?(.+?)_seeds$", arm)
        optimizer = m.group(1) if m else arm
        for job in sorted(os.listdir(arm_dir)):
            job_dir = os.path.join(arm_dir, job)
            eig = os.path.join(job_dir, "eigen_tracking.csv")
            if not os.path.isfile(eig):
                continue
            tags_path = os.path.join(job_dir, "section1_block_tags.csv")
            jm = re.match(r"job_idx_(\d+)$", job)
            job_idx = int(jm.group(1)) if jm else -1
            runs.append(
                Run(
                    family=family,
                    optimizer=canonical_optimizer(optimizer),
                    seed=JOB_IDX_TO_SEED.get(job_idx, job_idx),
                    job_idx=job_idx,
                    path=job_dir,
                    measures=pd.read_csv(eig),
                    tags=(
                        pd.read_csv(tags_path)
                        if os.path.isfile(tags_path)
                        else pd.DataFrame()
                    ),
                )
            )
    return runs


def eigen_panel(
    runs: list,
    tol: float = STEP_TOL_DEFAULT,
    drop_lone_arms: bool = True,
    align_seeds: bool = True,
) -> tuple:
    """Stack every run's eigen-tracking rows onto one shared checkpoint grid.

    Returns ``(panel, info)``. ``panel`` carries the raw CSV columns with
    ``arm, architecture, family, optimizer, seed, matched_step`` prepended;
    ``info`` records what the two filters removed, for the caller to print.

    Three things happen here that every Section-3 script needs identically:

    * **Clustering.** SOAP is measured on its own grid (LM ``34 + 576k`` against
      the other arms' ``576k``; ViT ``27 + 575k`` against ``576k``, so the offset
      there drifts from +27 to -27 across training). Rows are keyed on
      :func:`checkpoint_map`'s shared label, and the realised cluster diameter is
      checked against ``2 * tol`` -- single linkage can chain two clusters into
      one once more grids enter the pool, and that must fail loudly rather than
      quietly averaging two measurement occasions together.
    * **Lone-arm labels.** SOAP's transient first probe (LM 34, ViT 27) has no
      counterpart in any other arm, so it is dropped rather than compared
      against nothing.
    * **Seed alignment.** LM Kaon stops at 9216 on two seeds and 9792 on the
      third. Intersecting each arm's grid across its seeds keeps the late-half
      window over the same steps for every seed, matching what
      ``compute_paper_quantities.align_seeds`` does.
    """
    step_map = checkpoint_map(runs, tol)
    frames = []
    for run in runs:
        df = run.measures.copy()
        df.insert(0, "matched_step", [
            matched_step_of(step_map, s) for s in df["global_step"]
        ])
        df.insert(0, "seed", run.seed)
        df.insert(0, "optimizer", run.optimizer)
        df.insert(0, "family", optimizer_family(run.optimizer))
        df.insert(0, "architecture", run.family)
        df.insert(0, "arm", os.path.basename(os.path.dirname(run.path)))
        frames.append(df)
    if not frames:
        return pd.DataFrame(), {}
    panel = pd.concat(frames, ignore_index=True)

    span = panel.groupby("matched_step")["global_step"].agg(lambda s: s.max() - s.min())
    worst = int(span.max()) if len(span) else 0
    if worst > 2 * tol:
        offenders = span[span > 2 * tol]
        raise SystemExit(
            f"checkpoint clustering failed: cluster diameter {worst} exceeds "
            f"2*tol = {2 * tol:g} at matched_step(s) "
            f"{sorted(int(s) for s in offenders.index)}. Single linkage has "
            f"chained separate measurement occasions together; lower --step-tol."
        )

    info = {
        "n_runs": len(runs),
        "step_tol": float(tol),
        "max_cluster_diameter": worst,
        "n_labels": int(panel["matched_step"].nunique()),
        "dropped_lone_arm": [],
        "dropped_seed_align": 0,
    }

    if drop_lone_arms:
        per_label = panel.groupby("matched_step")["optimizer"].nunique()
        lone = sorted(int(s) for s in per_label[per_label < 2].index)
        if lone:
            info["dropped_lone_arm"] = lone
            panel = panel[~panel["matched_step"].isin(lone)].reset_index(drop=True)

    if align_seeds:
        keep = []
        for _, sub in panel.groupby(["architecture", "optimizer"], sort=False):
            n_seeds = sub["seed"].nunique()
            counts = sub.groupby("matched_step")["seed"].nunique()
            shared = counts[counts == n_seeds].index
            keep.append(sub[sub["matched_step"].isin(shared)])
        aligned = pd.concat(keep, ignore_index=True) if keep else panel
        info["dropped_seed_align"] = int(len(panel) - len(aligned))
        panel = aligned

    info["n_rows"] = int(len(panel))
    return panel, info


# Columns E and F both derive. Kept in one place so the two scripts cannot end
# up with different guard sets or a different sign convention.
EOS_GUARD_COLS = ("grad_norm", "update_norm", "full_update_grad_cosine")


def eos_frame(panel: pd.DataFrame) -> pd.DataFrame:
    """Add the EoS coordinate and the Eq.(6) channels to an eigen panel.

    Two logged conventions matter and are *not* re-applied here:

    * ``full_update_grad_cosine`` is already sign-flipped at logging time, so a
      descent step has ``cos > 0``. It is used as logged.
    * ``ritz_resid_*`` is already relative (residual over eigenvalue). G reads it
      as logged; nothing in this module renormalizes it.

    ``guard_ok`` marks the rows on which the coordinate is defined
    (``gnorm > 0``, ``unorm > 0``, ``cos > 0``). Rows with ``cos <= 0`` are
    ascent steps in the first-order sense; they are flagged, never silently
    dropped, so the caller can count and report them.
    """
    df = panel.copy()
    A = df["actual_update_rayleigh"].astype(float)
    gnorm = df["grad_norm"].astype(float)
    unorm = df["update_norm"].astype(float)
    cos = df["full_update_grad_cosine"].astype(float)
    lmax = df["eig_0"].astype(float)

    df["A"] = A
    df["gnorm"] = gnorm
    df["unorm"] = unorm
    df["cos"] = cos
    df["lmax"] = lmax

    finite = np.isfinite(A) & np.isfinite(gnorm) & np.isfinite(unorm) & np.isfinite(cos)
    df["guard_ok"] = finite & (gnorm > 0) & (unorm > 0) & (cos > 0)
    df["ascent_step"] = finite & (cos <= 0)

    ok = df["guard_ok"].to_numpy()
    nan = np.full(len(df), np.nan)

    # -g'Delta: the first-order gain per unit step, positive on a descent step.
    gdotd = np.where(ok, gnorm * unorm * cos, nan)
    eta_eff = np.where(ok, unorm**2 / gdotd, nan)

    df["gdotd"] = gdotd
    df["eta_eff"] = eta_eff
    df["rho_dir"] = eta_eff * A
    df["rho_max"] = eta_eff * lmax          # counterfactual, not a trajectory property
    df["A_over_lmax"] = np.where(lmax > 0, A / lmax, nan)
    df["efficiency"] = 1.0 - df["rho_dir"] / 2.0

    # Eq. (6) channels. ``scale`` drops the 1/2: a constant factor shifts no log
    # spread and no rank correlation.
    df["scale"] = np.where(lmax > 0, gnorm**2 / lmax, nan)
    df["align"] = cos**2
    df["exposure"] = df["A_over_lmax"]
    df["Phi_model"] = df["scale"] * df["align"] / df["exposure"]
    return df


def probe_reduction(df: pd.DataFrame) -> np.ndarray:
    """``probe_loss_reduction``, or the relative before/after drop if absent."""
    if "probe_loss_reduction" in df.columns:
        return df["probe_loss_reduction"].to_numpy(dtype=float)
    before = df["probe_loss_before"].to_numpy(dtype=float)
    after = df["probe_loss_after"].to_numpy(dtype=float)
    return np.where(before > 0, (before - after) / before, np.nan)


def log_sd(values) -> float:
    """Population sd of the natural log, NaN unless >= 2 positive finite values."""
    v = np.asarray(values, dtype=float)
    v = v[np.isfinite(v) & (v > 0)]
    if v.size < 2:
        return float("nan")
    return float(np.std(np.log(v), ddof=0))


def max_over_min(values) -> float:
    """Spread as a plain ratio, NaN unless every value is positive and finite."""
    v = np.asarray(values, dtype=float)
    v = v[np.isfinite(v) & (v > 0)]
    if v.size < 2:
        return float("nan")
    return float(v.max() / v.min())


def window_frame(df: pd.DataFrame, window: str) -> pd.DataFrame:
    """``all`` or the late half of each (architecture, optimizer, seed) run."""
    if window == "all":
        return df
    if window == "late":
        return late_half(df, group_cols=["architecture", "optimizer", "seed"])
    raise ValueError(f"unknown window {window!r}")
