program: train_lm.py
method: bayes
metric:
  name: best_eval_loss
  goal: minimize
command:
- ${env}
- ${interpreter}
- -u
- ${program}
- --config=config/lm_adam.yaml
parameters:
  lr:
    distribution: log_uniform_values
    min: 1.0e-06
    max: 0.03
  weight_decay:
    distribution: log_uniform_values
    min: 0.005
    max: 0.25
  beta1:
    distribution: uniform
    min: 0.8
    max: 0.95
  beta2:
    distribution: uniform
    min: 0.85
    max: 0.995
  eigen_tracking_enabled:
    value: false
  effective_curvature_tracking_enabled:
    value: false
  precond_criterion_enabled:
    value: false
  use_wandb:
    value: true
  wandb_project:
    value: tune-adam-lm-fwedu-16
run_cap: 16
